### ISSUE TITLE
Clarified Installation Steps

### ISSUE THREAD

**Issue by yamerooo123** [ManShum812/ReflectedXSS-Finder#1]
After git clone the repo 
1. Initialize a Go module: go mod init <folder name>
2. Install HTTP2 dependencies: go get golang.org/x/net/http2
3. go build main.go
4. sudo chmod 777 main.go
5. Create input.txt
6. ./main or go run main.go

This works for me.

**Comment by ManShum812** [comment]
Thank you for pointing this out, @yamerooo123!

If anyone has trouble installing the tool, feel free to follow these steps:

1. Clone the Repository
2. Initialize a Go module : go mod init
3. Install the HTTP2 dependencies : go get golang.org/x/net/http2
4. Build the project : go build main.go
5. Set Permissions if needed : sudo chmod 777 main
6. Create the input.txt file
7. Run the script : ./main

I appreciate your feedback!

Closing this issue now. If you have any more questions or suggestions, feel free to open a new issue.
